version: '3.8'

services:
  web:
    image: random-restaurant-fastapi
    ports:
      - "18080:18080"
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=development
    command: uvicorn main:app --host 0.0.0.0 --port 18080
